
#ifndef _GRUB_ERR
#define	_GRUB_ERR

#define GRUB_MAX_ERRMSG		256

typedef enum
{
	GRUB_ERR_NONE = 0,
	GRUB_ERR_TEST_FAILURE,
	GRUB_ERR_BAD_MODULE,
	GRUB_ERR_OUT_OF_MEMORY,
	GRUB_ERR_BAD_FILE_TYPE,
	GRUB_ERR_FILE_NOT_FOUND,
	GRUB_ERR_FILE_READ_ERROR,
	GRUB_ERR_BAD_FILENAME,
	GRUB_ERR_UNKNOWN_FS,
	GRUB_ERR_BAD_FS,
	GRUB_ERR_BAD_NUMBER,
	GRUB_ERR_OUT_OF_RANGE,
	GRUB_ERR_UNKNOWN_DEVICE,
	GRUB_ERR_BAD_DEVICE,
	GRUB_ERR_READ_ERROR,
	GRUB_ERR_WRITE_ERROR,
	GRUB_ERR_UNKNOWN_COMMAND,
	GRUB_ERR_INVALID_COMMAND,
	GRUB_ERR_BAD_ARGUMENT,
	GRUB_ERR_BAD_PART_TABLE,
	GRUB_ERR_UNKNOWN_OS,
	GRUB_ERR_BAD_OS,
	GRUB_ERR_NO_KERNEL,
	GRUB_ERR_BAD_FONT,
	GRUB_ERR_NOT_IMPLEMENTED_YET,
	GRUB_ERR_SYMLINK_LOOP,
	GRUB_ERR_BAD_COMPRESSED_DATA,
	GRUB_ERR_MENU,
	GRUB_ERR_TIMEOUT,
	GRUB_ERR_IO,
	GRUB_ERR_ACCESS_DENIED,
	GRUB_ERR_EXTRACTOR,
	GRUB_ERR_NET_BAD_ADDRESS,
	GRUB_ERR_NET_ROUTE_LOOP,
	GRUB_ERR_NET_NO_ROUTE,
	GRUB_ERR_NET_NO_ANSWER,
	GRUB_ERR_NET_NO_CARD,
	GRUB_ERR_WAIT,
	GRUB_ERR_BUG,
	GRUB_ERR_NET_PORT_CLOSED,
	GRUB_ERR_NET_INVALID_RESPONSE,
	GRUB_ERR_NET_UNKNOWN_ERROR,
	GRUB_ERR_NET_PACKET_TOO_BIG,
	GRUB_ERR_NET_NO_DOMAIN,
	GRUB_ERR_EOF,
	GRUB_ERR_BAD_SIGNATURE
}
grub_err_t;

#include <grub/types.h>

grub_err_t
grub_error(
	grub_err_t errno,
	UINT8* errstr,
	...
);

#endif